name: Create Archive
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: clone submodule
      run: |
        cd BurntToast
        git init
        git config core.sparsecheckout true
        git remote add origin https://github.com/Windos/BurntToast.git
        echo BurntToast > .git/info/sparse-checkout
        git pull origin main
        cd ..
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1.8.9
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
